apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-template
  name: nginx-template
spec:
  containers:
    - image: nginx
      name: nginx-template
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
